/*-
 * WSDL stubs for:  http://www.aswinanand.com/sendsms.php?wsdl
 *   Generated by:  sakiv
 *           Date:  Sun Dec  5 15:27:26 2010
 *        Emitter:  Objective-C
 */

#import "Proxy.h"

/*-
 *   Web Service:  SendSMS
 * Documentation:  <not documented>
 */
/*-
 *   Method Name:  sendSMSToMany
 * Documentation:  Sends the same SMS to multiple phone numbers. Give your 10 digit
 *                 phone number for user ID. Separate each phone number with a
 *                 semicolon(';').
 */

@interface sendSMSToMany : Proxy {
	NSString *url;
	NSString *soapMessage;
}

- (id) initWithUrl:(NSString *)urlWithString;

// update the parameter list for the invocation.
- (void) setParameters:(NSString*) in_uid in_pwd:(NSString*) in_pwd in_phone:(NSString*) in_phone in_msg:(NSString*) in_msg;

@end; /* sendSMSToMany */


/*-
 * Web Service:  SendSMS
 */
@interface SendSMSService : NSObject 

+ (id) sendSMSToMany:(NSString*) in_uid in_pwd:(NSString*) in_pwd in_phone:(NSString*) in_phone in_msg:(NSString*) in_msg;

@end;


/*-
 * End of WSDL document at http://www.aswinanand.com/sendsms.php?wsdl
 */
